pods:
  name: helloapp
  image: ilaymord/helloapp
  tag: latest

replicaCount: 3

containerPort: 5001

service:
  type: LoadBalancer
  port: 5001
  targetPort: 5001

limits:
  memory: "128Mi"
  cpu: "500m"
requests:
  memory: "64Mi"
  cpu: "250m"